"""fix_column_names_and_constraints

Revision ID: 22b3e0d7b6c6
Revises: update_erd_compliance
Create Date: 2025-09-11 13:13:46.332848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22b3e0d7b6c6"
down_revision: Union[str, None] = "update_erd_compliance"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversation")
    op.create_index(op.f("ix_conversation_id"), "conversation", ["id"], unique=False)
    op.create_index(
        op.f("ix_conversation_user_id"), "conversation", ["user_id"], unique=False
    )
    op.drop_constraint(
        op.f("conversations_user_id_fkey"), "conversation", type_="foreignkey"
    )
    op.create_foreign_key(None, "conversation", "user", ["user_id"], ["id"])
    op.drop_index(op.f("idx_feedback_message_user"), table_name="feedback")
    op.drop_constraint(op.f("uq_feedback_message_user"), "feedback", type_="unique")
    op.drop_index(op.f("ix_feedback_message_id"), table_name="feedback")
    op.create_index(
        op.f("ix_feedback_message_id"), "feedback", ["message_id"], unique=True
    )
    op.create_index(
        "idx_feedbacks_message_user",
        "feedback",
        ["message_id", "user_id"],
        unique=False,
    )
    op.drop_constraint(op.f("feedback_user_id_fkey"), "feedback", type_="foreignkey")
    op.create_foreign_key(None, "feedback", "user", ["user_id"], ["id"])

    # First, add the sender column with nullable=True
    op.add_column(
        "message",
        sa.Column(
            "sender", sa.Enum("user", "assistant", name="message_role"), nullable=True
        ),
    )

    # Copy data from role to sender column
    op.execute(
        "UPDATE message SET sender = role::text::message_role WHERE role IS NOT NULL"
    )

    # Make sender column non-nullable
    op.alter_column("message", "sender", nullable=False)

    op.drop_index(op.f("idx_messages_conversation_created"), table_name="message")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="message")
    op.drop_index(op.f("ix_messages_id"), table_name="message")
    op.drop_index(op.f("ix_messages_parent_message_id"), table_name="message")
    op.create_index(
        "idx_message_conversation_created",
        "message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_conversation_id"), "message", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    op.drop_constraint(
        op.f("messages_parent_message_id_fkey"), "message", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("messages_conversation_id_fkey"), "message", type_="foreignkey"
    )
    op.create_foreign_key(None, "message", "conversation", ["conversation_id"], ["id"])
    op.drop_column("message", "role")
    op.drop_column("message", "parent_message_id")
    op.drop_index(op.f("ix_users_email"), table_name="user")
    op.drop_index(op.f("ix_users_id"), table_name="user")
    op.drop_index(op.f("ix_users_username"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_users_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_users_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "user", ["email"], unique=True)
    op.add_column(
        "message",
        sa.Column("parent_message_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "message",
        sa.Column(
            "role",
            postgresql.ENUM("user", "assistant", "system", name="message_role"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_conversation_id_fkey"),
        "message",
        "conversation",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("messages_parent_message_id_fkey"),
        "message",
        "message",
        ["parent_message_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_index(op.f("ix_message_conversation_id"), table_name="message")
    op.drop_index("idx_message_conversation_created", table_name="message")
    op.create_index(
        op.f("ix_messages_parent_message_id"),
        "message",
        ["parent_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_id"), "message", ["id"], unique=False)
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "message",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_messages_conversation_created"),
        "message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.drop_column("message", "sender")
    op.drop_constraint(None, "feedback", type_="foreignkey")
    op.create_foreign_key(
        op.f("feedback_user_id_fkey"),
        "feedback",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("idx_feedbacks_message_user", table_name="feedback")
    op.drop_index(op.f("ix_feedback_message_id"), table_name="feedback")
    op.create_index(
        op.f("ix_feedback_message_id"), "feedback", ["message_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_feedback_message_user"),
        "feedback",
        ["message_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_feedback_message_user"),
        "feedback",
        ["message_id", "user_id"],
        unique=False,
    )
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.create_foreign_key(
        op.f("conversations_user_id_fkey"),
        "conversation",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_conversation_user_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_id"), table_name="conversation")
    op.create_index(
        op.f("ix_conversations_user_id"), "conversation", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_id"), "conversation", ["id"], unique=False)
    # ### end Alembic commands ###
