"""create_missing_tool_approvals_table

Revision ID: 6c6598a9eb26
Revises: 1ce64a959f7d
Create Date: 2026-03-10 13:59:13.889216

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c6598a9eb26"
down_revision: str | None = "1ce64a959f7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("interrupt_id", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("tool_call_id", sa.String(length=255), nullable=False),
        sa.Column("original_args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("modified_args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "decision",
            sa.Enum("ACCEPT", "EDIT", "REJECT", name="decision_type"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_approvals_conversation_id"),
        "tool_approvals",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_approvals_decided_at"),
        "tool_approvals",
        ["decided_at"],
        unique=False,
    )
    op.create_index(op.f("ix_tool_approvals_id"), "tool_approvals", ["id"], unique=False)
    op.create_index(
        op.f("ix_tool_approvals_interrupt_id"),
        "tool_approvals",
        ["interrupt_id"],
        unique=False,
    )
    op.create_index(op.f("ix_tool_approvals_user_id"), "tool_approvals", ["user_id"], unique=False)
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_index(op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes")
    op.drop_table("checkpoint_writes")
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index(op.f("ix_mcp_oauth_tokens_id"), table_name="mcp_oauth_tokens")
    op.drop_index(op.f("ix_mcp_oauth_tokens_server_name"), table_name="mcp_oauth_tokens")
    op.drop_index(op.f("ix_mcp_oauth_tokens_state"), table_name="mcp_oauth_tokens")
    op.drop_index(op.f("ix_mcp_oauth_tokens_user_id"), table_name="mcp_oauth_tokens")
    op.drop_table("mcp_oauth_tokens")
    op.drop_table("checkpoint_migrations")
    op.create_index(op.f("ix_agent_model_configs_id"), "agent_model_configs", ["id"], unique=False)
    op.create_index(
        op.f("ix_agent_model_configs_user_id"),
        "agent_model_configs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_images_document_id"),
        "document_images",
        ["document_id"],
        unique=False,
    )
    op.drop_column("documents", "file_size")
    op.drop_index(op.f("ix_hitl_interrupts_status_expires_at"), table_name="hitl_interrupts")
    op.create_index(
        op.f("ix_hitl_interrupts_assistant_message_id"),
        "hitl_interrupts",
        ["assistant_message_id"],
        unique=False,
    )
    op.create_foreign_key(None, "hitl_interrupts", "messages", ["assistant_message_id"], ["id"])
    op.drop_column("messages", "extra_metadata")
    op.drop_column("messages", "citations")
    op.create_index(op.f("ix_model_providers_id"), "model_providers", ["id"], unique=False)
    op.create_index(
        op.f("ix_model_providers_user_id"), "model_providers", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_task_plans_conversation_order"), table_name="task_plans")
    op.drop_index(op.f("ix_task_plans_status"), table_name="task_plans")
    op.create_index(
        "idx_task_plan_conversation_order",
        "task_plans",
        ["conversation_id", "task_order"],
        unique=False,
    )
    op.drop_column("task_plans", "estimated_duration_minutes")
    op.drop_column("task_plans", "started_at")
    op.drop_column("task_plans", "completion_confidence")
    op.drop_column("task_plans", "retry_count")
    op.drop_column("task_plans", "actual_duration_minutes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_plans",
        sa.Column("actual_duration_minutes", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "task_plans",
        sa.Column(
            "retry_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "task_plans",
        sa.Column(
            "completion_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "task_plans",
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "task_plans",
        sa.Column(
            "estimated_duration_minutes",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index("idx_task_plan_conversation_order", table_name="task_plans")
    op.create_index(op.f("ix_task_plans_status"), "task_plans", ["status"], unique=False)
    op.create_index(
        op.f("ix_task_plans_conversation_order"),
        "task_plans",
        ["conversation_id", "task_order"],
        unique=False,
    )
    op.drop_index(op.f("ix_model_providers_user_id"), table_name="model_providers")
    op.drop_index(op.f("ix_model_providers_id"), table_name="model_providers")
    op.add_column(
        "messages",
        sa.Column(
            "citations",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "extra_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "hitl_interrupts", type_="foreignkey")
    op.drop_index(op.f("ix_hitl_interrupts_assistant_message_id"), table_name="hitl_interrupts")
    op.create_index(
        op.f("ix_hitl_interrupts_status_expires_at"),
        "hitl_interrupts",
        ["status", "expires_at"],
        unique=False,
    )
    op.add_column(
        "documents",
        sa.Column("file_size", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_document_images_document_id"), table_name="document_images")
    op.drop_index(op.f("ix_agent_model_configs_user_id"), table_name="agent_model_configs")
    op.drop_index(op.f("ix_agent_model_configs_id"), table_name="agent_model_configs")
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("checkpoint_migrations_pkey")),
    )
    op.create_table(
        "mcp_oauth_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("server_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("server_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("refresh_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "token_type",
            sa.VARCHAR(length=50),
            server_default=sa.text("'Bearer'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("scope", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("code_verifier", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("mcp_oauth_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mcp_oauth_tokens_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "server_name",
            name=op.f("uq_mcp_oauth_user_server"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_mcp_oauth_tokens_user_id"),
        "mcp_oauth_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_mcp_oauth_tokens_state"), "mcp_oauth_tokens", ["state"], unique=False)
    op.create_index(
        op.f("ix_mcp_oauth_tokens_server_name"),
        "mcp_oauth_tokens",
        ["server_name"],
        unique=False,
    )
    op.create_index(op.f("ix_mcp_oauth_tokens_id"), "mcp_oauth_tokens", ["id"], unique=False)
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name=op.f("checkpoint_blobs_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_blobs_thread_id_idx"),
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("checkpoint_writes_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_writes_thread_id_idx"),
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("checkpoints_pkey")
        ),
    )
    op.create_index(op.f("checkpoints_thread_id_idx"), "checkpoints", ["thread_id"], unique=False)
    op.drop_index(op.f("ix_tool_approvals_user_id"), table_name="tool_approvals")
    op.drop_index(op.f("ix_tool_approvals_interrupt_id"), table_name="tool_approvals")
    op.drop_index(op.f("ix_tool_approvals_id"), table_name="tool_approvals")
    op.drop_index(op.f("ix_tool_approvals_decided_at"), table_name="tool_approvals")
    op.drop_index(op.f("ix_tool_approvals_conversation_id"), table_name="tool_approvals")
    op.drop_table("tool_approvals")
    # ### end Alembic commands ###
