"""add_hitl_interrupts_table

Revision ID: h1i2j3k4l5m6
Revises: f6a7b8c9d0e1
Create Date: 2026-03-09 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM
from sqlalchemy.dialects.postgresql import JSONB, UUID

# revision identifiers, used by Alembic.
revision: str = "h1i2j3k4l5m6"
down_revision: str | None = "f6a7b8c9d0e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create hitl_interrupts table for durable interrupt lifecycle tracking."""

    # Create the status enum
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE hitl_interrupt_status AS ENUM (
                'pending', 'resolving', 'resolved', 'expired'
            );
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
        """
    )

    op.create_table(
        "hitl_interrupts",
        sa.Column(
            "id",
            sa.String(255),
            primary_key=True,
            comment="interrupt_id generated by LangGraph or the graph wrapper",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
        ),
        # Scope
        sa.Column(
            "conversation_id",
            UUID(as_uuid=True),
            sa.ForeignKey("conversations.id"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("thread_id", sa.String(255), nullable=False),
        sa.Column(
            "assistant_message_id",
            UUID(as_uuid=True),
            sa.ForeignKey("messages.id"),
            nullable=True,
        ),
        # Lifecycle
        sa.Column(
            "status",
            PG_ENUM(
                "pending",
                "resolving",
                "resolved",
                "expired",
                name="hitl_interrupt_status",
                create_type=False,
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("resolution_source", sa.String(50), nullable=True),
        # Payload
        sa.Column(
            "action_requests_json",
            JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    # Additional indexes
    op.create_index(
        "ix_hitl_interrupts_conversation_id",
        "hitl_interrupts",
        ["conversation_id"],
    )
    op.create_index("ix_hitl_interrupts_user_id", "hitl_interrupts", ["user_id"])
    op.create_index("ix_hitl_interrupts_thread_id", "hitl_interrupts", ["thread_id"])
    op.create_index(
        "ix_hitl_interrupts_assistant_message_id",
        "hitl_interrupts",
        ["assistant_message_id"],
    )
    op.create_index("ix_hitl_interrupts_status", "hitl_interrupts", ["status"])
    op.create_index("ix_hitl_interrupts_expires_at", "hitl_interrupts", ["expires_at"])
    op.create_index(
        "ix_hitl_interrupts_status_expires_at",
        "hitl_interrupts",
        ["status", "expires_at"],
    )


def downgrade() -> None:
    """Drop hitl_interrupts table."""
    op.drop_index("ix_hitl_interrupts_status_expires_at", table_name="hitl_interrupts")
    op.drop_index("ix_hitl_interrupts_expires_at", table_name="hitl_interrupts")
    op.drop_index("ix_hitl_interrupts_status", table_name="hitl_interrupts")
    op.drop_index("ix_hitl_interrupts_assistant_message_id", table_name="hitl_interrupts")
    op.drop_index("ix_hitl_interrupts_thread_id", table_name="hitl_interrupts")
    op.drop_index("ix_hitl_interrupts_user_id", table_name="hitl_interrupts")
    op.drop_index("ix_hitl_interrupts_conversation_id", table_name="hitl_interrupts")
    op.drop_table("hitl_interrupts")
    op.execute("DROP TYPE IF EXISTS hitl_interrupt_status")
