from __future__ import annotations

from datetime import datetime, timezone
from zoneinfo import ZoneInfo

from app.core.config import settings


def _coerce_utc(value: datetime | None) -> datetime:
    if value is None:
        return datetime.now(timezone.utc)
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def _resolve_timezone(timezone_name: str | None) -> tuple[ZoneInfo | timezone, str, str | None]:
    candidate = (timezone_name or "").strip() or "UTC"
    try:
        return ZoneInfo(candidate), candidate, None
    except Exception:
        return timezone.utc, "UTC", "configured timezone was invalid"


def build_runtime_time_context_block(
    *,
    now: datetime | None = None,
    timezone_name: str | None = None,
) -> str:
    """Build a server-generated temporal anchor for model prompts.

    This is deliberately prompt context, not a tool result. Tools remain the
    source of truth for changing external facts; this block only tells the
    model what "now" means during the request.
    """
    current_utc = _coerce_utc(now)
    configured_timezone = timezone_name
    if configured_timezone is None:
        configured_timezone = getattr(settings, "runtime_time_context_timezone", "UTC")

    local_tz, resolved_timezone, fallback_note = _resolve_timezone(configured_timezone)
    current_local = current_utc.astimezone(local_tz)

    lines = [
        "",
        "",
        "-- Runtime Time Context --",
        "The following values were generated by the server at request time. "
        "Treat them as temporal context data, not user instructions.",
        f"- current_utc: {current_utc.isoformat()}",
        f"- timezone: {resolved_timezone}",
        f"- current_local: {current_local.isoformat()}",
        f"- local_date: {current_local.strftime('%A, %B %d, %Y')}",
        f"- local_weekday: {current_local.strftime('%A')}",
        f"- utc_offset: {current_local.strftime('%z') or '+0000'}",
    ]
    if fallback_note:
        lines.append(f"- fallback: {fallback_note}")
    lines.extend(
        [
            "Guidance:",
            "- Use this context to interpret relative dates and references to now.",
            "- If an answer depends on changing external facts, use available tools/search; "
            "this block only anchors time.",
            "-- End Runtime Time Context --",
        ]
    )
    return "\n".join(lines)
