"""Model for tracking durable HITL interrupt lifecycle state."""

import enum

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, func
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.models.base import Base


class HITLInterruptStatus(str, enum.Enum):
    """Lifecycle status of a HITL interrupt session."""

    PENDING = "pending"  # Awaiting human decision
    RESOLVING = "resolving"  # Decision received; graph being resumed (transient)
    FAILED = "failed"  # Claimed continuation terminated unsuccessfully
    RESOLVED = "resolved"  # Workflow resumed successfully
    EXPIRED = "expired"  # Timeout elapsed before decision


class HITLInterrupt(Base):
    """
    Durable lifecycle record for a single HITL interrupt session.

    Created when the graph pauses for human approval and updated as the
    session moves through its lifecycle (pending → resolving → resolved /
    expired).
    """

    __tablename__ = "hitl_interrupts"

    id = Column(
        String(255),
        primary_key=True,
        comment="interrupt_id generated by LangGraph or the graph wrapper",
    )
    created_at = Column(DateTime(timezone=True), default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True), default=func.now(), onupdate=func.now(), nullable=False
    )

    # Scope identifiers
    conversation_id = Column(
        UUID(as_uuid=True),
        ForeignKey("conversations.id"),
        nullable=False,
        index=True,
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )
    thread_id = Column(String(255), nullable=False, index=True)

    # The assistant message that represents the paused state (for recovery)
    assistant_message_id = Column(
        UUID(as_uuid=True), ForeignKey("messages.id"), nullable=True, index=True
    )

    # Lifecycle
    status = Column(
        SQLEnum(
            HITLInterruptStatus,
            name="hitl_interrupt_status",
            create_type=False,
            values_callable=lambda x: [e.value for e in x],
        ),
        nullable=False,
        default=HITLInterruptStatus.PENDING,
        index=True,
    )
    expires_at = Column(DateTime(timezone=True), nullable=False, index=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    resolved_by_user_id = Column(UUID(as_uuid=True), nullable=True)
    resolution_source = Column(String(50), nullable=True)  # "user", "timeout", "cancel"

    # Stored pending actions (serialized ToolInterruptRequest list)
    action_requests_json = Column(JSONB, nullable=False, default=list)

    # Device context (optional - set when interrupt originated from a client device)
    device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("client_devices.id"),
        nullable=True,
        index=True,
    )

    # Additional metadata for the interrupt (device context, tool provenance, etc.)
    interrupt_metadata_json = Column(JSONB, nullable=False, default=dict)

    # Execution-scope for client-local tool interrupts; used to detect stale resume
    session_id = Column(String(255), nullable=True, index=True)
    catalog_version = Column(Integer, nullable=True)
    tool_instance_id = Column(String(64), nullable=True)

    # Relationships
    conversation = relationship("Conversation", backref="hitl_interrupts")
    user = relationship("User", backref="hitl_interrupts")
    device = relationship("ClientDevice", backref="hitl_interrupts")

    def __repr__(self) -> str:
        return (
            f"<HITLInterrupt(id={self.id!r}, status={self.status.value!r}, "
            f"conversation_id={self.conversation_id})>"
        )
